### ISSUE TITLE
⌨️ What errors do we want to track?

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#174]
Do we want to track `SyntaxErrors`, `NotImplementedError` en `LoadError`s (etc) in AppSignal? We don't do that now for a lot of implementations, because we only track `StandardError`s, see #168 for fixing mis-usage and my upcoming blog post.

It can however be a good addition to track more errors than those subclassed from `StandardError`. What do you think?

See https://gist.github.com/tombruijn/cad99e541231ba7283f4467dbf68da2b for more details about which error does what + the docs http://ruby-doc.org/core-2.3.1/Exception.html

Edit: As requested:

- https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/7028024986
- https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/conversation/11111116983
- https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/11598818180

## TODO

- [x] Review #356 
- [x] Ship an alpha release
- [x] Test the alpha release on staging https://github.com/appsignal/appsignal-server/pull/2543
- [x] Get users to try out the new Exception handling (see Intercom)
- [x] Add automatic intercom message to people upgrading from `< 2.4.0` to `>= 2.4.0` about gem version 2.4 capturing a lot more errors - written, now to enable once blog post is published

**Comment by thijsc** [comment]
In general we want our gem to never crash the host app. What would be the downside of catching these?

**Comment by tombruijn** [comment]
Downside: More data?

There isn't really a downside, but I was curious if there was a conscious decision to only catch StandardError for most integrations (and Exception in a few other cases)?

Catching these extra errors doesn't cause a greater danger of crashing the app, we'll register those errors and then re-raise them to let the normal error handling do its thing

**Comment by thijsc** [comment]
This was done already right?

**Comment by tombruijn** [comment]
Nope. Not yet. I still have a branch to update this.

**Comment by tombruijn** [comment]
My idea would be not to rescue Exception (the main exception class in Ruby), but the following subclasses: `NoMemoryError, ScriptError, SecurityError, StandardError, SystemStackError`.

We wouldn't necessarily want to track/report occurrences of `SystemExit` and `SignalExit` when a user kills/stops an application. Those are not really an error we necessarily want to report all the time.

For example, when `exit 1` is called and you want to track it as an error you could also use `Appsignal.send_error(MyCustomExitError.new("oh shit, this went horribly wrong"))` instead for those occurrences you want to report.

`SignalException` is more debatable if we want to track that or not. An outside source tells the application to exit. Is that always an error?

Also, because of how our integration is set up, when a Rails app is processing an action and `killall -9 ruby` is executed, this exception will be reported, but when the Rails app is idle (and no other code is running that AppSignal tracks exceptions in) the error will not be reported.

**Comment by tombruijn** [comment]
Idea from @matsimitsu:

Track everything (Exception), add default list of suggested ignored exceptions (SignalExit and SystemExit, for example) for new users in `appsignal.yml`.

Detect in processor an upgrade and mail users about the changes in the type of exceptions we track. We can also send users an changelog diff when they upgrade.

**Comment by midN** [comment]
Hello,

As i was debugging some cases when Airbrake was reporting our Prod errors while Appsignal was not i ended up in this PR.

If it makes any difference i would vote for rescuing all `Exceptions` since like in our case, it turned out we had some Gem, or even couple of them, that are raising their Exceptions not based on `StandardError` but rather just `Exception`.
Like the above idea, adding `SignalException` and other hardcore errors to default ignored list + README would be sufficient enough to avoid some shitstorm i believe :)

I also believe there are tons of other gems + projects out there where people did not really think about the good-practice and just based their custom Exceptions on `Exception` class.

 (Some of your new customer)

**Comment by tombruijn** [comment]
Thanks again for reporting the issue! So far we've decided to go with the strategy commented earlier https://github.com/appsignal/appsignal-ruby/issues/174#issuecomment-321752002
which should end up in v2.4 of the gem

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/11598818180
(new comment for intercom hook)

**Comment by tombruijn** [comment]
#356 is merged. Now we want until 2.4 is released to set the Intercom message

**Comment by tombruijn** [comment]
@midN we've shipped this change in version `2.4.0.alpha.1`. Please try it out and let us know if you run into any problems with this!

**Comment by tombruijn** [comment]
Closing. Will ship this on Tuesday
