### ISSUE TITLE
Log to STDOUT when set through option

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#184]
Let's give the option to the user instead of using a workaround by tricking the system into thinking it's on Heroku (the only time we log to stdout on purpose) `DYNO=foo ruby app.rb`

``` yml
# config/appsignal.yml

log_path: ~
# ~ is nil

# or
log: stdout
```

`log: stdout` has my preference

When no path is writable it should log to stdout by default.

See also https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/6239874634 

---

## TODO
- [x] Ruby process log to stdout #190 
- [x] Extension log to stdout https://github.com/appsignal/appsignal-agent/pull/195
- [ ] ~~Agent process log to stdout, RFC0002 https://github.com/appsignal/rfcs/pull/2~~
- [x] Read appsignal.log on agent connection failure https://github.com/appsignal/appsignal-agent/issues/197

**Comment by tombruijn** [comment]
Last addition: output last lines from `appsignal.log` to STDOUT on agent connection failure, when the agent fails to start, added in gem v2.0.4.
 
Closing

**Comment by tonytonyjan** [comment]
I set `log: stdout` with v2.2.1, but it still writes to `log/appsignal.log`, having no idea how to diagnosis.
