### ISSUE TITLE
Full Ruby 2.6 and Rails 6 support

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#464]
Follow up of https://github.com/appsignal/appsignal-ruby/pull/460#issuecomment-456115360

## TODO

- [x] Ruby: Fix ERB warning - https://github.com/appsignal/appsignal-ruby/pull/480
- [x] Ruby: Fix Psych deprecation warning - https://github.com/appsignal/appsignal-ruby/pull/479
- [x] Rails: Fix deprecation warning about `Module#parent_name` - https://github.com/appsignal/appsignal-ruby/pull/478

## Logs

Users will see these messages on the `appsignal install <Push API key>` command run. Maybe we can fix that for Rails 6 before it's out.

```
DEPRECATION WARNING: `Module#parent_name` has been renamed to `module_parent_name`. `parent_name` is deprecated and will be removed in Rails 6.1. (called from install_for_rails at /home/travis/build/appsignal/appsignal-ruby/lib/appsignal/cli/install.rb:80)

/home/travis/build/appsignal/appsignal-ruby/lib/appsignal/cli/install.rb:252: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/home/travis/build/appsignal/appsignal-ruby/lib/appsignal/cli/install.rb:252: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```

**Comment by tombruijn** [comment]
Closing. See linked PRs
