### ISSUE TITLE
Ruby gem 4.0

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#667]
Plans for Ruby gem 4.0. This includes breaking changes, new features and removal of deprecations.

### Features

- [x] Rails runner support - #641 
- [x] Support multiple errors - #1152
- [x] ~Enable Rake instrumentation by default? - #1135~
  - I don't think it's a good idea. It's fine if people can enable it with the config option.

### Quality of life improvements

- [x] #315 
- [x] Load rails app in diagnose CLI - #1225 
- [x] Start AppSignal only once. If it's started more than once, ignore the secondary start.
  - #1217
  - 🚨 Breaking change
- [x] Support some way for people to configure AppSignal using Ruby like `Appsignal.configure`? We could add a config option to the YAML file / env var that says something `auto_start: false`, and then apps can call `Appsignal.start` manually (and we'll internally call `Appsignal._start` to start AppSignal to help differentiate start calls).
  - [x] Deprecate `initial_config` from `Config.new`
  - https://github.com/appsignal/appsignal-ruby/pull/1196
- [x] Amend sample data
  - 🚨 Breaking change
  - #1209 

#### Integrations
- [x] Rails error reporter
  - Report errors using the multiple errors mechanism, not make duplicate transactions itself
  - Report unhandled errors, because we ignore duplicate reports using the multiple errors mechanism
  - #1240
- [x] Loader mechanism - #1192 
  - 🚨 Breaking change
- [x] Rake: set default namespace to "rake"
  - 🚨 Breaking change

#### Always reporting data

- [x] Always register a `at_exit` callback to report the error with which the Ruby process crashed
  - Could resolve #808
  - @1218
- [x] Always register a `at_exit` callback to call `Appsignal.stop`
- [x] Add option to disable at_exit reporting: `enable_at_exit_reporter: false`
- [x] ~Always call `Appsignal.stop` on all rake tasks? Instrumented or not? Downside: slight delay in every rake execution when stopping.~ The `stop` call takes too long.

#### Instrumentation helpers
- [x] Remove the `listen_for_error` helper
  - 🚨 Breaking change
- [x] Deprecate the `listen_for_error` helper without replacement. Tell people to use `rescue => error; Appsignal.report_error(error)`
- [x] ~`Appsignal.send_error` copies current instrumented context like the Rails error handler. Blocked on the 'report multiple errors' item.~
  - 🚨 Breaking change
  - Let's keep the behavior for `send_error` different. We should recommend people to use `report_error` for this behavior.
- [x] Have `Appsignal.set_*` helpers set the metadata on the transaction in the context of a `report_error`, `set_error` and `send_error` block.
  - #1216
  - That way we can document one way of setting this metadata on transactions, and not one way for the `Appsignal` module and another for the `Transaction` class.
  - Change the current transaction to the newly created one or use a different Thread variable to make sure it's never lost.
  - 🚨 Breaking change
- [x] `Appsignal.monitor` helper to replace `monitor_transaction` - #1161

### Maintenance
- [x] Remove deprecated Heartbeats behavior - #1243
- [x] Remove `APPSIGNAL_APP_ENV` behavior in Config initializer. This is now done by `Appsignal.start`
- [x] Freeze the Appsignal::Config#config_hash after `Appsignal.start`. Don't allow apps to modify the config after start, or arrays in the config.
  - 🚨 Breaking change
- [x] Remove all deprecations listed below.
  - 🚨 Breaking change
- [x] Deprecate `Transaction`'s request and options arguments to `Transaction.new`
- [x] Deprecate `Transaction`'s request and options arguments to `Transaction.create`
- [x] Deprecate `Transaction::GenericRequest`
- [x] Deprecate `Transaction#set_http_or_background_action` - #1175
- [x] Refactor Delayed::Job integration to not use `monitor_transaction` - #1171
- [x] Refactor Shoryuken integration to not use `monitor_transaction` - #1170 
- [x] Move [Capistrano integration to `Integrations` module namespace](https://github.com/appsignal/appsignal-ruby/blob/35dc01de7c697c6f8e387a6537ee730a3d5561a2/lib/appsignal/integrations/capistrano/capistrano_2_tasks.rb#L4-L6). #1164

## Documentation
- [x] Merging of sample data. Rename `set_*` helpers to `add_*` - https://github.com/appsignal/appsignal-docs/pull/2076
- [x] Update exception handling page for multiple error support - https://github.com/appsignal/appsignal-docs/pull/2075
- [x] Document `enable_at_exit_reporter`
- [x] Document `sleep 5` (or some amount) for `enable_at_exit_reporter` on short lived containers
- [x] Rails runner performance monitoring with `Appsignal.monitor` - https://github.com/appsignal/appsignal-docs/pull/2027
- [x] Mention `listen_for_error` helper is removed in 4.0
- [x] Document `Appsignal.configure`
- [x] Document loader mechanism for
  - [x] Sinatra
  - [x] Grape
  - [x] Hanami
  - [x] Padrino
  - [x] A multiple of the above 
- [x] `Appsignal.set_session_data` - https://github.com/appsignal/appsignal-docs/pull/1990
- [x] `Appsignal.set_headers` - https://github.com/appsignal/appsignal-docs/pull/1990
- [x] `Appsignal.set_tags` accepts booleans - https://github.com/appsignal/appsignal-docs/pull/1991
- [x] `Appsignal.monitor` and `Appsignal.monitor_and_stop` - https://github.com/appsignal/appsignal-docs/pull/1998
- [x] Rails initializer change - https://github.com/appsignal/appsignal-docs/pull/1999

## Deprecated

Remove the following in the next major version:

- [x] Remove initial config from Config initializer?
- [x] Remove `APPSIGNAL_INACTIVE_ON_CONFIG_FILE_ERROR` output in diagnose, because the ENV var was removed.
- [x] Remove `Transaction::FRONTEND` constant
- [x] Go through all to do comments
- [x] Remove `Transaction` sample data 'metadata'
- [x] Remove `Transaction.new`'s request and options arguments
- [x] Remove `Transaction.create`'s request and options arguments
- [x] Remove `Transaction#set_http_or_background_action`
- [x] Remove `Transaction#set_http_or_background_queue_start`
- [x] Remove `Transaction#params=`
- [x] Remove `Transaction::GenericRequest`
- [x] Remove `Appsignal.monitor_transaction` and `Appsignal.monitor_single_transaction`
- [x] Remove `appsignal.action` and `appsignal.route` as action name values from the AbstractMiddleware, see #1116
- [x] Remove `Appsignal.start_logger` - https://github.com/appsignal/appsignal-ruby/pull/1119
- [x] Remove `Appsignal.set_error` `tags` and `namespace` arguments
- [x] Remove `Appsignal.send_error` `tags` and `namespace` arguments
- [x] Remove `Appsignal::Rack::StreamingListener`
- [x] Remove `Appsignal::Rack::GenericInstrumentation`, also remove the `const_missing` redirect
- [x] Remove `Appsignal::Grape` constants, also remove the `const_missing` redirect
- [x] Update config options behavior here: https://github.com/appsignal/appsignal-ruby/blob/1e77564aa52ec1eb1a743cddf2782f483fe94b4c/lib/appsignal/config.rb#L544-L548
- [x] Update config to stop on YAML file error: https://github.com/appsignal/appsignal-ruby/blob/470d58132270115215093c9cffd16e52829ef4c4/lib/appsignal/config.rb#L422-L426
- [x] Remove debug option from Ruby and extension config
- [x] Remove transaction debug option from Ruby and extension config
- [x] Remove skip_session_data option from Ruby and extension config
- [x] Remove working_dir_path option from Ruby and extension config
- [x] `working_dir_path` deprecation: https://github.com/appsignal/appsignal-ruby/blob/1cde9f911c34a8f9406ae55552b938931f9cc222/lib/appsignal/config.rb#L367-L372
  - Remove this code
- [x] Remove minutely probe constant redirect.
  - [x] `Minutely` module was renamed to `Probes` in #1065. [Remove this code.](https://github.com/appsignal/appsignal-ruby/blob/94fdbac0d34225299f3494105cb94de471e33238/lib/appsignal.rb#L291-L305)
  - [x] Remove the `const_missing` redirector.
- [x] Remove Sidekiq plugin [`const_missing` here](https://github.com/appsignal/appsignal-ruby/blob/1e77564aa52ec1eb1a743cddf2782f483fe94b4c/lib/appsignal/hooks.rb#L76)
- [x] Remove `Appsignal::Probes.probes.register`
- [x] Remove `Appsignal::Helpers::Metrics::set_host_gauge` and `Appsignal::Helpers::Metrics::set_process_gauge`
  - Related issue: https://github.com/appsignal/appsignal-agent/issues/425
  - Remove all `set_host_*` metric helpers here: https://github.com/appsignal/appsignal-ruby/blob/9922140f3a76c5aad45a4db44a5052ee7da05c88/lib/appsignal/helpers/metrics.rb#L17-L31

**Comment by tombruijn** [comment]
[Ruby gem 4](https://blog.appsignal.com/2024/08/23/appsignal-for-ruby-version-4-0.html) has been released!
