### ISSUE TITLE
Rename Minutely module to Probes

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#813]
To be consistent with other integrations, rename the `Minutely` module to the `Probes` module.

## TODO

- [x] Rename the `Minutely` module to `Probes.
- [x] Set up a class alias so that `Minutely` will continue to work.
    - [x] Deprecate the `Minutely` module.
    - See this code example of how we've done this before: https://github.com/appsignal/appsignal-ruby/blob/2c12f99bc66ee558d189ae09ea4823b867e2c192/lib/appsignal/hooks.rb#L73-L87
- [x] Update the public docs to use the `Probes` module.

**Comment by tombruijn** [comment]
Hi @AnshulRiyal, This isn't can't be closed yet. No one is currently working on it. I was thinking of changing the Probes module to a class, then it would work. Let me know if you have other questions :)

```diff
diff --git lib/appsignal/probes.rb lib/appsignal/probes.rb
index cdc360ff..4cf5f65f 100644
--- lib/appsignal/probes.rb
+++ lib/appsignal/probes.rb
@@ -1,5 +1,5 @@
 module Appsignal
-  module Probes
+  class Probes
   end
 end
 
diff --git lib/appsignal/probes/mri.rb lib/appsignal/probes/mri.rb
index 51bf4ac8..fcb5c83d 100644
--- lib/appsignal/probes/mri.rb
+++ lib/appsignal/probes/mri.rb
@@ -1,5 +1,5 @@
 module Appsignal
-  module Probes
+  class Probes
     class MriProbe
       # @api private
       def self.dependencies_present?
diff --git lib/appsignal/probes/sidekiq.rb lib/appsignal/probes/sidekiq.rb
index d4d09fde..73cbc3bb 100644
--- lib/appsignal/probes/sidekiq.rb
+++ lib/appsignal/probes/sidekiq.rb
@@ -1,5 +1,5 @@
 module Appsignal
-  module Probes
+  class Probes
     class SidekiqProbe
       # @api private
       attr_reader :config

```

**Comment by AnshulRiyal** [comment]
@tombruijn Please let me know if i can raise the PR for remaning the modules to classes 🙇

**Comment by tombruijn** [comment]
@AnshulRiyal you're welcome to send in a PR to fix the issue as described :)
