### ISSUE TITLE
Ruby VM/GC Dashboard

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-ruby#850]
https://github.com/appsignal/appsignal-ruby/tree/vm-stats

## TODO

- [X] Move off mocking (noun)-based testing in existing Ruby VM tests
- [x] Add VM/GC metrics
- [x] Check metrics for compatibility with Ruby 3.2
- [x] Add Magic Dashboard

**Comment by tombruijn** [comment]
Added in Ruby gem 3.1
