### ISSUE TITLE
Replace Hanami monkeypatch with middleware

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-ruby#911]
## TODO

- [x] Add a Hanami Rack middleware on load, preferrably automated
- [x] Take out the Monkeypatch - see https://github.com/hanami/controller/issues/445
- [x] Update our implementation to only use the monkeypatch on Hanami < 2.2.
- [x] Update our implementation to read from the param added in [this PR](https://github.com/hanami/controller/pull/446) if present

---

- [Internal discussion](https://appsignal.slack.com/archives/CNPP953E2/p1672595304248889)

**Comment by tombruijn** [comment]
Tracking issue for the change to report the action name in the request env in the Hanami project: https://github.com/hanami/controller/issues/445

**Comment by tombruijn** [comment]
PR merged in the Hanami project. We can pick this up.
